FROM python:3.12.3-slim

WORKDIR /app

ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
ENV UV_COMPILE_BYTECODE=1

COPY pyproject.toml .
COPY uv.lock .
RUN pip install --no-cache-dir uv
RUN uv sync --frozen --no-install-project --no-dev

COPY src/agents/ ./agents/
COPY src/core/ ./core/
COPY src/memory/ ./memory/
COPY src/schema/ ./schema/
COPY src/service/ ./service/
COPY src/run_service.py .

CMD ["python", "run_service.py"]

# requirements.txt 파일 복사 및 패키지 설치
#COPY docker/requirements.txt /app/requirements.txt  
RUN pip install --no-cache-dir --upgrade pip
#RUN pip install --no-cache-dir -r requirements.txt

RUN pip install \
    pymupdf \
    chromadb \
    #torch==2.6.0 -f https://download.pytorch.org/whl/cpu/torch_stable.html \
    beautifulsoup4 \
    #sentence-transformers \
    langchain \
    langchain-community\
   # langchain_huggingface
    rank_bm25